spring:
  profiles:
    active: dev

#配置日志
logging:
  #配置日志文件路径
  #采用相对路径方式将日志文件输出到【log\record.log】
  level:
    web: ${logging.level.web}
  file:
    name: log\record.log

custom:
  path:
    pic:
      zoomPicPath: ${custom.path.pic.zoomPicPath}
      rotatePicPath: ${custom.path.pic.rotatePicPath}
      waterMarkPicPath: ${custom.path.pic.waterMarkPicPath}
      tailorPicPath: ${custom.path.pic.tailorPicPath}
      transferFormatPicPath: ${custom.path.pic.transferFormatPicPath}
    rsa:
      phonePublicKeyPath: ${custom.path.rsa.phonePublicKeyPath}
      phonePrivateKeyPath: ${custom.path.rsa.phonePrivateKeyPath}