#配置日志
logging:
  level:
    web: debug

custom:
  path:
    pic:
      zoomPicPath: E://pic/zoomPic/
      rotatePicPath: E://pic/rotatePic/
      waterMarkPicPath: E://pic/waterMarkPic/
      tailorPicPath: E://pic/tailorPic/
      transferFormatPicPath: E://pic/transferFormat/
    rsa:
      # 手机RSA加密专用秘钥
      phonePublicKeyPath: E://rsa/publicKey.pem
      phonePrivateKeyPath: E://rsa/privateKey.pem